// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_ld_between_two_snps
double calculate_ld_between_two_snps(IntegerVector snp1, IntegerVector snp2);
RcppExport SEXP _HaploTraitR_calculate_ld_between_two_snps(SEXP snp1SEXP, SEXP snp2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type snp1(snp1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type snp2(snp2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_ld_between_two_snps(snp1, snp2));
    return rcpp_result_gen;
END_RCPP
}
// calculate_ld_matrix
NumericMatrix calculate_ld_matrix(IntegerMatrix snp_matrix);
RcppExport SEXP _HaploTraitR_calculate_ld_matrix(SEXP snp_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type snp_matrix(snp_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_ld_matrix(snp_matrix));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP convertGenoBi2Numeric_c(SEXP);
RcppExport SEXP find_nearby_snps_c(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_HaploTraitR_calculate_ld_between_two_snps", (DL_FUNC) &_HaploTraitR_calculate_ld_between_two_snps, 2},
    {"_HaploTraitR_calculate_ld_matrix", (DL_FUNC) &_HaploTraitR_calculate_ld_matrix, 1},
    {"convertGenoBi2Numeric_c", (DL_FUNC) &convertGenoBi2Numeric_c, 1},
    {"find_nearby_snps_c",      (DL_FUNC) &find_nearby_snps_c,      3},
    {NULL, NULL, 0}
};

RcppExport void R_init_HaploTraitR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
