# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_ld_between_two_snps <- function(snp1, snp2) {
    .Call(`_HaploTraitR_calculate_ld_between_two_snps`, snp1, snp2)
}

calculate_ld_matrix <- function(snp_matrix) {
    .Call(`_HaploTraitR_calculate_ld_matrix`, snp_matrix)
}

